/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/registro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrar nueva cuenta de estudiante (RF-01 a RF-04, UC-AUT-01) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nombre: string;
                        /** Format: email */
                        correo: string;
                        /**
                         * Format: password
                         * @description RF-03, mínimo 8 caracteres
                         */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Cuenta creada; sesión iniciada automáticamente. El acceso a funcionalidades financieras permanece bloqueado hasta aceptar el consentimiento (RF-49). */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description JWT válido por 7 días (RF-06) */
                            token?: string;
                            usuario?: components["schemas"]["Usuario"];
                        };
                    };
                };
                400: components["responses"]["ValidacionError"];
                /** @description El correo ya está registrado (RF-02) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iniciar sesión (RF-05 a RF-07, UC-AUT-02) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        correo: string;
                        /** Format: password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Autenticado. Se crea una fila en `sesiones` con el `jti` del token. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            token?: string;
                            usuario?: components["schemas"]["Usuario"];
                        };
                    };
                };
                /** @description Correo o contraseña incorrectos — mensaje genérico, sin indicar cuál dato falló (AUT-02/CA02). */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Cuenta bloqueada temporalmente tras 5 intentos fallidos (RF-07, D-04). */
                423: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cerrar sesión — revoca el JWT actual (RF-08, UC-AUT-02) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sesión revocada. El `jti` queda marcado `revocada=true` en la tabla `sesiones`. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["NoAutenticado"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil del usuario autenticado (incluye estado de consentimiento) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usuario"];
                    };
                };
                401: components["responses"]["NoAutenticado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consentimiento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aceptar el consentimiento informado (RF-47 a RF-49, UC-CON-01)
         * @description Habilita el acceso a las funcionalidades financieras. Sin esta aceptación, todo endpoint marcado como "requiere consentimiento" responde 403 (código CONSENTIMIENTO_REQUERIDO).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Versión del texto de consentimiento mostrado y aceptado (RF-48) */
                        versionTexto: string;
                    };
                };
            };
            responses: {
                /** @description Consentimiento registrado. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usuario"];
                    };
                };
                401: components["responses"]["NoAutenticado"];
                /** @description El usuario ya había aceptado el consentimiento previamente. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transacciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar transacciones del usuario autenticado
         * @description Base del listado que alimenta el indicador "N.º de registros por semana" (RF-09/TRX-01, DSH-01).
         */
        get: {
            parameters: {
                query?: {
                    /** @description RF-41 — filtro de periodo del dashboard */
                    periodo?: components["parameters"]["PeriodoFiltro"];
                    tipo?: "ingreso" | "egreso";
                    categoriaId?: string;
                    pagina?: components["parameters"]["Pagina"];
                    tamanoPagina?: components["parameters"]["TamanoPagina"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            datos?: components["schemas"]["Transaccion"][];
                            total?: number;
                        };
                    };
                };
                401: components["responses"]["NoAutenticado"];
                403: components["responses"]["ConsentimientoRequerido"];
            };
        };
        put?: never;
        /**
         * Registrar transacción manual (RF-09 a RF-12, UC-TRX-01)
         * @description `origen` se fija en "manual". Si `tipo` es "egreso", el backend evalúa el umbral de gasto hormiga vigente y guarda su snapshot en `umbral_hormiga_aplicado` (RF-38, D-08) — el cliente nunca envía estos dos campos.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransaccionInput"];
                };
            };
            responses: {
                201: components["responses"]["TransaccionCreada"];
                400: components["responses"]["ValidacionError"];
                401: components["responses"]["NoAutenticado"];
                403: components["responses"]["ConsentimientoRequerido"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transacciones/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RecursoId"];
            };
            cookie?: never;
        };
        /** Obtener una transacción */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecursoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["TransaccionCreada"];
                401: components["responses"]["NoAutenticado"];
                403: components["responses"]["ConsentimientoRequerido"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        /**
         * Editar transacción (RF-13, RF-15, UC-TRX-02)
         * @description Recalcula dashboard y meta de ahorro asociada tras el cambio (RF-15).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecursoId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransaccionInput"];
                };
            };
            responses: {
                200: components["responses"]["TransaccionCreada"];
                400: components["responses"]["ValidacionError"];
                401: components["responses"]["NoAutenticado"];
                403: components["responses"]["ConsentimientoRequerido"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        post?: never;
        /**
         * Eliminar transacción (RF-14, RF-15, UC-TRX-02)
         * @description Confirmación previa del usuario ocurre en el cliente (RF-14); este endpoint elimina de forma permanente y dispara el recálculo de dashboard/meta de ahorro (RF-15).
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecursoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eliminada. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["NoAutenticado"];
                403: components["responses"]["ConsentimientoRequerido"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar categorías disponibles — predefinidas + propias del usuario (RF-36, RF-37, CAT-01) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK — incluye las predefinidas (globales) y las creadas por el usuario autenticado. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Categoria"][];
                    };
                };
                401: components["responses"]["NoAutenticado"];
            };
        };
        put?: never;
        /**
         * Crear categoría propia (RF-53, CAT-01)
         * @description La categoría creada es privada del usuario (`esPredefinida=false`, `usuarioId` = el del token); no la ven otros estudiantes.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nombre: string;
                    };
                };
            };
            responses: {
                /** @description Creada. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Categoria"];
                    };
                };
                400: components["responses"]["ValidacionError"];
                401: components["responses"]["NoAutenticado"];
                /** @description Ya existe una categoría (predefinida o propia) con ese nombre para este usuario (RF-53). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categorias/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RecursoId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Renombrar categoría propia (RF-54) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecursoId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nombre: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Categoria"];
                    };
                };
                400: components["responses"]["ValidacionError"];
                401: components["responses"]["NoAutenticado"];
                /** @description La categoría es predefinida; no admite edición (RF-54). */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                404: components["responses"]["NoEncontrado"];
            };
        };
        post?: never;
        /**
         * Eliminar categoría propia (RF-54)
         * @description Solo si no tiene transacciones asociadas (ver HU CAT-01, CA06).
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecursoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eliminada. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["NoAutenticado"];
                /** @description La categoría es predefinida; no admite eliminación (RF-54). */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                404: components["responses"]["NoEncontrado"];
                /** @description La categoría tiene transacciones asociadas; reasígnalas antes de eliminarla (CA06). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metas-ahorro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar metas de ahorro con progreso calculado en tiempo real (RF-32, RF-33, RF-34, UC-AHO-02) */
        get: {
            parameters: {
                query?: {
                    estado?: "activa" | "cumplida" | "inactiva";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MetaAhorroConProgreso"][];
                    };
                };
                401: components["responses"]["NoAutenticado"];
                403: components["responses"]["ConsentimientoRequerido"];
            };
        };
        put?: never;
        /**
         * Crear meta de ahorro (RF-30, RF-31, RF-32, UC-AHO-01)
         * @description La fecha límite es opcional, a elección del estudiante (D-14); si se omite, la meta queda como "sin fecha límite".
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nombre: string;
                        /**
                         * Format: double
                         * @description RF-31
                         */
                        montoObjetivo: number;
                        /**
                         * Format: date
                         * @description Opcional (D-14); si se define, debe ser futura (RF-31)
                         */
                        fechaLimite?: string | null;
                    };
                };
            };
            responses: {
                201: components["responses"]["MetaAhorroCreada"];
                400: components["responses"]["ValidacionError"];
                401: components["responses"]["NoAutenticado"];
                403: components["responses"]["ConsentimientoRequerido"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metas-ahorro/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RecursoId"];
            };
            cookie?: never;
        };
        /** Ver progreso de una meta de ahorro (UC-AHO-02) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecursoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["MetaAhorroCreada"];
                401: components["responses"]["NoAutenticado"];
                403: components["responses"]["ConsentimientoRequerido"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Eliminar o desactivar meta de ahorro
         * @description Si la meta ya tiene transacciones vinculadas, el sistema la marca como "inactiva" en lugar de eliminarla (regla de negocio de AHO-01, detalle del backlog); si no tiene transacciones vinculadas, se elimina de forma permanente.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecursoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Meta marcada como inactiva (tenía transacciones vinculadas). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MetaAhorroConProgreso"];
                    };
                };
                /** @description Meta eliminada (sin transacciones vinculadas). */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["NoAutenticado"];
                403: components["responses"]["ConsentimientoRequerido"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocr/escanear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Escanear boleta con OCR (RF-16 a RF-19, UC-OCR-01)
         * @description Envía la imagen a Google Vision API vía backend (D-09: credenciales nunca en el cliente). Genera una `SugerenciaTransaccion` con `origen="ocr"` que debe pasar por el flujo de confirmación (POST /sugerencias/{id}/confirmar o /descartar, UC-CNF-01) antes de persistirse como transacción. Tiempo máximo de respuesta: 10 s (ver RequerimientosNoFuncionales.md, RNF-02).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        imagen: string;
                    };
                };
            };
            responses: {
                /** @description Sugerencia generada con el monto detectado, editable antes de confirmar (RF-18). */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SugerenciaTransaccion"];
                    };
                };
                401: components["responses"]["NoAutenticado"];
                403: components["responses"]["ConsentimientoRequerido"];
                /** @description No se pudo detectar un monto válido en la imagen (FE1/FE3 de UC-OCR-01). El cliente debe ofrecer "Reintentar" o derivar a registro manual (RF-19). */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sugerencias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar sugerencias pendientes de confirmación (RF-20, UC-CNF-01)
         * @description Incluye sugerencias generadas por OCR y por importación de Gmail. Las expiradas (>24h, RF-22) no se listan.
         */
        get: {
            parameters: {
                query?: {
                    estado?: "pendiente" | "confirmada" | "descartada";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SugerenciaTransaccion"][];
                    };
                };
                401: components["responses"]["NoAutenticado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sugerencias/{id}/confirmar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RecursoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirmar (con o sin edición) una sugerencia como transacción (RF-21, UC-CNF-01 flujo básico/FA1)
         * @description Crea la transacción definitiva con los valores de la sugerencia o los editados por el estudiante. `categoriaId` es obligatorio porque `transacciones.categoria_id` no admite nulo (ver DiagramaEntidadRelacion.md). El `usuario_id` de la transacción resultante se toma del token, nunca del cliente (RF-50).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecursoId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: double
                         * @description Sobrescribe el monto detectado si el estudiante lo editó
                         */
                        monto?: number;
                        /** @enum {string} */
                        tipo?: "ingreso" | "egreso";
                        /** Format: date */
                        fecha?: string;
                        /** Format: uuid */
                        categoriaId: string;
                        /** Format: uuid */
                        metaAhorroId?: string | null;
                    };
                };
            };
            responses: {
                201: components["responses"]["TransaccionCreada"];
                400: components["responses"]["ValidacionError"];
                401: components["responses"]["NoAutenticado"];
                404: components["responses"]["NoEncontrado"];
                /** @description La sugerencia expiró a las 24 horas y ya fue descartada automáticamente (RF-22, FE1 de UC-CNF-01). */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sugerencias/{id}/descartar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RecursoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Descartar una sugerencia sin persistir transacción (RF-21, UC-CNF-01 FA2) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecursoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sugerencia eliminada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["NoAutenticado"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gmail/conectar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Iniciar conexión OAuth 2.0 con Gmail (RF-23, UC-GML-01)
         * @description Devuelve la URL de autorización de Google (scope `gmail.readonly` únicamente).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            urlAutorizacion?: string;
                        };
                    };
                };
                401: components["responses"]["NoAutenticado"];
                403: components["responses"]["ConsentimientoRequerido"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gmail/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Callback OAuth de Google (uso interno del flujo de autorización)
         * @description Google redirige aquí tras la autorización. El backend intercambia el `code` por tokens, los cifra con AES-256-GCM (RF-24, D-06) y los persiste en `conexiones_gmail`; luego redirige de vuelta a la app móvil. No se invoca directamente desde el cliente.
         */
        get: {
            parameters: {
                query: {
                    code: string;
                    state: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirección a la app móvil (deep link) tras completar o cancelar la autorización (CA02 de GML-01). */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gmail/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar estado de la conexión con Gmail */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConexionGmail"];
                    };
                };
                401: components["responses"]["NoAutenticado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gmail/conexion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revocar el acceso a Gmail (RF-25, UC-GML-01 CA03)
         * @description Elimina el token almacenado y detiene la lectura futura de notificaciones.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Acceso revocado. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["NoAutenticado"];
                /** @description El usuario no tiene una conexión de Gmail activa. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/resumen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resumen consolidado del dashboard financiero (RF-37, RF-39, RF-40, RF-41, UC-DSH-01)
         * @description Incluye ingresos, egresos y ahorro del periodo (RF-40), monto total agrupado por categoría (RF-37, CAT-01) y el porcentaje de gastos hormiga sobre el total de egresos del periodo (RF-39, CAT-02), calculado con la marca automática por umbral, no con el criterio del estudiante (D-15). Todos los valores se calculan en tiempo real, sin precálculo (detalle de DSH-01).
         *     Solo considera **consumo corriente**: las transacciones vinculadas a una meta de ahorro quedan excluidas de todos los totales (RF-59, D-16), porque mueven plata entre "disponible" y "apartado" en vez de entrar o salir del presupuesto. Apartar plata en una meta, entonces, no reduce `ahorroTotal`. Lo acumulado en cada meta se consulta en `GET /metas-ahorro`.
         */
        get: {
            parameters: {
                query?: {
                    /** @description RF-41 — filtro de periodo del dashboard */
                    periodo?: components["parameters"]["PeriodoFiltro"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardResumen"];
                    };
                };
                401: components["responses"]["NoAutenticado"];
                403: components["responses"]["ConsentimientoRequerido"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encuesta-sus/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verificar si el estudiante ya respondió la encuesta SUS (RF-44, UC-USA-01 CA03) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            completada?: boolean;
                        };
                    };
                };
                401: components["responses"]["NoAutenticado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encuesta-sus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enviar respuestas de la encuesta SUS (RF-42, RF-43, RF-44, UC-USA-01)
         * @description El backend calcula el puntaje con la fórmula estándar SUS y lo persiste; las respuestas individuales no se devuelven al estudiante después del envío (detalle de USA-01), solo la confirmación.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 10 ítems del cuestionario estándar SUS, escala Likert 1-5 */
                        respuestas: number[];
                    };
                };
            };
            responses: {
                /** @description Respuesta registrada. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date-time */
                            fechaRespuesta?: string;
                        };
                    };
                };
                400: components["responses"]["ValidacionError"];
                401: components["responses"]["NoAutenticado"];
                /** @description El estudiante ya respondió la encuesta previamente (RF-44). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/errores/resumen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar conteo de errores agrupado por módulo y periodo (RF-46, UC-CAL-01)
         * @description Requiere rol `investigador` (RF-46, D-05 no aplica aquí porque `registros_error` no tiene `usuario_id` — ver ERD).
         */
        get: {
            parameters: {
                query?: {
                    modulo?: string;
                    desde?: string;
                    hasta?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            modulo?: string;
                            /** @description Agrupación por día/semana/mes según los parámetros desde/hasta */
                            periodo?: string;
                            total?: number;
                        }[];
                    };
                };
                401: components["responses"]["NoAutenticado"];
                /** @description El usuario autenticado no tiene rol `investigador`. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @description Código estable para el cliente, ej. CONSENTIMIENTO_REQUERIDO, VALIDACION */
            codigo?: string;
            mensaje?: string;
        };
        Usuario: {
            /** Format: uuid */
            id?: string;
            nombre?: string;
            /** Format: email */
            correo?: string;
            /** @enum {string} */
            rol?: "estudiante" | "investigador";
            consentimientoAceptado?: boolean;
            /** Format: date-time */
            fechaConsentimiento?: string | null;
            versionConsentimiento?: string | null;
            /** Format: date-time */
            fechaRegistro?: string;
        };
        Categoria: {
            /** Format: uuid */
            id?: string;
            nombre?: string;
            /** @description true = global, no editable/eliminable por el usuario (D-13) */
            esPredefinida?: boolean;
        };
        TransaccionInput: {
            /**
             * Format: double
             * @description RF-10
             */
            monto: number;
            /** @enum {string} */
            tipo: "ingreso" | "egreso";
            /** Format: uuid */
            categoriaId: string;
            /**
             * Format: uuid
             * @description Vincula la transacción a una meta de ahorro propia (RF-33). Con valor, la transacción es un movimiento de ahorro (D-16): si `tipo` es "egreso" es un aporte a la meta; si es "ingreso", un retiro. Los movimientos de ahorro nunca se marcan como gasto hormiga y quedan fuera de todos los totales del dashboard (RF-57 a RF-59). Responde 404 si la meta es de otro usuario y 409 si está inactiva.
             */
            metaAhorroId?: string | null;
            /**
             * Format: date
             * @description No admite fecha futura (RF-11)
             */
            fecha: string;
            /** @description Criterio propio del estudiante sobre si el egreso fue innecesario (RF-55, D-15). Opcional; omitirlo o enviarlo null significa "sin opinión", que NO equivale a false. No afecta la marca automática `esGastoHormiga`, que el cliente nunca puede modificar. */
            esGastoHormigaUsuario?: boolean | null;
        };
        Transaccion: components["schemas"]["TransaccionInput"] & {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            origen?: "manual" | "ocr" | "gmail";
            /** @description Marca automática por umbral, calculada por el backend (RF-38). Inmutable: alimenta el indicador de la investigación (D-15). Siempre `false` en movimientos de ahorro (con `metaAhorroId`) y en ingresos, cualquiera sea el monto (RF-58, D-16). */
            esGastoHormiga?: boolean;
            /**
             * Format: double
             * @description Snapshot del umbral vigente al momento de crear el egreso (D-08); null para ingresos
             */
            umbralHormigaAplicado?: number | null;
            imagenUrl?: string | null;
            /** Format: date-time */
            fechaCreacion?: string;
        };
        MetaAhorroConProgreso: {
            /** Format: uuid */
            id?: string;
            nombre?: string;
            /** Format: double */
            montoObjetivo?: number;
            /**
             * Format: date
             * @description null = sin fecha límite (D-14)
             */
            fechaLimite?: string | null;
            /** @enum {string} */
            estado?: "activa" | "cumplida" | "inactiva";
            /**
             * Format: double
             * @description Calculado en tiempo real, RF-33
             */
            montoAhorrado?: number;
            /**
             * Format: double
             * @description Limitado a 100 aunque el monto ahorrado lo supere (AHO-02/FA1)
             */
            porcentajeCumplimiento?: number;
            /** Format: date-time */
            fechaCreacion?: string;
        };
        SugerenciaTransaccion: {
            /** Format: uuid */
            id?: string;
            /** Format: double */
            monto?: number;
            /** @enum {string} */
            tipo?: "ingreso" | "egreso";
            /** Format: date */
            fecha?: string;
            /** @enum {string} */
            origen?: "ocr" | "gmail";
            /** @enum {string} */
            estado?: "pendiente" | "confirmada" | "descartada";
            /**
             * Format: date-time
             * @description 24 h desde la creación (RF-22)
             */
            fechaExpiracion?: string;
            /** Format: date-time */
            fechaCreacion?: string;
        };
        ConexionGmail: {
            conectado?: boolean;
            /** @enum {string|null} */
            estado?: "activo" | "revocado" | null;
            /** Format: date-time */
            fechaConexion?: string | null;
        };
        DashboardResumen: {
            /** @enum {string} */
            periodo?: "semana" | "mes";
            /** Format: date */
            fechaInicio?: string;
            /** Format: date */
            fechaFin?: string;
            /**
             * Format: double
             * @description Solo consumo corriente: excluye retiros de metas (RF-59, D-16)
             */
            ingresosTotal?: number;
            /**
             * Format: double
             * @description Solo consumo corriente: excluye aportes a metas (RF-59, D-16)
             */
            egresosTotal?: number;
            /**
             * Format: double
             * @description Superávit del periodo (`ingresosTotal - egresosTotal`, RF-40). De acá sale lo que el estudiante puede apartar en sus metas, así que apartar plata NO lo reduce (D-16). Lo acumulado por meta se consulta en `GET /metas-ahorro`.
             */
            ahorroTotal?: number;
            gastosPorCategoria?: {
                /** Format: uuid */
                categoriaId?: string;
                nombre?: string;
                /** Format: double */
                montoTotal?: number;
            }[];
            gastosHormiga?: {
                /** Format: double */
                montoTotal?: number;
                /** Format: double */
                porcentajeSobreEgresos?: number;
            };
        };
    };
    responses: {
        /** @description Error de validación de los datos enviados. */
        ValidacionError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Falta el token, es inválido, expiró o su sesión fue revocada (RF-51). */
        NoAutenticado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description El recurso no existe o no pertenece al usuario autenticado — mismo código de estado en ambos casos, por diseño anti-IDOR (RF-50, D-05). */
        NoEncontrado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description El usuario no ha aceptado el consentimiento informado; las funcionalidades financieras permanecen bloqueadas (RF-49). */
        ConsentimientoRequerido: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description OK */
        TransaccionCreada: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Transaccion"];
            };
        };
        /** @description OK */
        MetaAhorroCreada: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MetaAhorroConProgreso"];
            };
        };
    };
    parameters: {
        RecursoId: string;
        /** @description RF-41 — filtro de periodo del dashboard */
        PeriodoFiltro: "semana" | "mes";
        Pagina: number;
        TamanoPagina: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
